name: Release Plugin

on:
  push:
    tags:
      - 'v*' # Dieser Workflow startet automatisch, wenn du einen Tag wie "v1.0.0" pushst.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore "RiNnoFinTelegramm/Jellyfin.Plugin.RiNnoFinTelegramm.csproj"

      - name: Build
        run: dotnet build "RiNnoFinTelegramm/Jellyfin.Plugin.RiNnoFinTelegramm.csproj" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "RiNnoFinTelegramm/Jellyfin.Plugin.RiNnoFinTelegramm.csproj" --configuration Release --no-build --output ./publish

      - name: Zip Release
        run: |
          cd ./publish
          zip -r ../RiNnoFinTelegramm.zip ./*
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: RiNnoFinTelegramm.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Das ist der integrierte Key von GitHub, du musst keinen eigenen erstellen!
